### ISSUE TITLE
Installation - Defaults to Checked Boxes on UDC and VP If Exist

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/iPortal#10]
If the UDC and VP already exists, the boxes should not be checked. 

Also the language in the subsequent pop-ups refer to an entry that I didn't make, which is confusing. 

Substitute with "existing Virtual Proxy/UDC" would read better

**Comment by goldbergjeffrey** [comment]
Updated installer so that if the virtual proxy and UDC exist you will not be able to change the name, and if they don't exist they will be created.  No more check box activity.  They are still there, but they can't be acted upon.
