### ISSUE TITLE
iPortal login extremely slow after upgrade to 3.0

### ISSUE THREAD

**Issue by dustinbaxa** [eapowertools/iPortal#17]
When using iPortal with 2.2.4 it took about 5 seconds to login with a user and access the hub when logging in with one of the impersonated users. After upgrading to 3.0 it now takes anywhere between 30-40 seconds each time. I have updated the services.conf file after upgrading through both manual entries and the new method added by [Mr. Goldberg](https://github.com/eapowertools/iPortal/wiki/Update-services.conf-file-for-EAPowerTools-after-Qlik-Sense-Service-Dispatcher-update). I have spoken with others who are experiencing this same issue after upgrading. Logging in with my own personal credentials takes much less time (about 15 seconds, which actually has increased with the upgrade to 3.0 as well).

**Comment by goldbergjeffrey** [comment]
@dustinbaxa, looks like 3.0.1 may address Hub slowness on loading.  I'll keep open until you can verify improvement.

**Comment by goldbergjeffrey** [comment]
Resolved in 3.0.1 Qlik Sense Service Release available now at Qlik.com.

**Comment by dustinbaxa** [comment]
@goldbergjeffrey , Just upgraded to 3.0.1 and now my iPortal login is lightning fast! Thanks!
