### ISSUE TITLE
Root admins can edit published sheets

### ISSUE THREAD

**Issue by dustinbaxa** [eapowertools/iPortal#18]
I'm not sure if this is intended behavior or a bug but I wanted to post it. After installing iPortal, the RootAdmin(s) can completely edit published apps (edit published sheets, reload data, etc.) within the hub without needing to duplicate to "My Work". In my opinion, this would not be a best practice in a production environment. In order to fix this so that the RootAdmin cannot edit published sheets, I had to disable the rule: 

> _gss – Root Admin Group Rule 

and also change the resource filter of the rule: 

> _gss – Create App

 from App\* to App_*.

**Comment by levi-turner** [comment]
_gss – Root Admin Group Rule doesn't allow you to edit published apps unless the context is QMC and Hub (or Hub only)

It looks like gss – Create App has been stealth edited to be App_\* rather than App*.

**Comment by goldbergjeffrey** [comment]
Yes, this issue is resolved in the documentation.
