### ISSUE TITLE
Installation failure with customized install paths

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/iPortal#22]
I've already pinged Jeff about this but for public tracking: the iPortal install bombs when Qlik Sense is installed in any path but the default path.

It gets stuck trying to configure the iPortal Virtual Proxy: http://i.imgur.com/M0XB9bj.png

If you try to click next you are prompted with: http://i.imgur.com/JAk7TS0.png

In terms of a fix, there look to be relatively stable registry keys which can be leveraged to determine the install path:
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\QlikSenseRepositoryService or HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\QlikSenseRepositoryService
ImagePath = C:\Sense\Repository\Repository.exe –iscentral (where Sense is installed to C:\Sense)

If I were a better coder then I'd attempt a fix

**Comment by goldbergjeffrey** [comment]
Installer Resolves issue of Qlik Sense detection issues and hostname obstruction during installer.  Fixed in **[Latest Release Notes](https://github.com/eapowertools/iPortal/releases/latest)**
