### ISSUE TITLE
iPortal gss_setup_guide rules - fix

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/iPortal#25]
Under the "Import Apps" section, remove requirement to set custom properties on each app being imported, as well as the image of the example table showing custom properties on all apps. 

The only app that needs a custom property assigned is Executive Dashboard, which needs AppLevelMgmt.

The rules are functional without the need for app-level CP tagging unless you want an exception, such as Executive DB.

**Comment by goldbergjeffrey** [comment]
Completeish.  Left references for Governed Metrics Service in, but removed @QlikGroup property because it is not required on apps.
