### ISSUE TITLE
Instructions on security rules is not working

### ISSUE THREAD

**Issue by gustafssone** [eapowertools/iPortal#29]
If you follow the instructions at https://github.com/eapowertools/iPortal/blob/master/docs/gss_setup_guide.md you will see on rule number #2 and #8 (I noticed it on #8) that the NOT EQUAL (!=) is not working. See more info at http://help.qlik.com/en-US/sense/3.2/Subsystems/ManagementConsole/Content/operator-not-equal.htm . Suggestions is to change to NOT instead.

In my scenario I use a modified version, similar to https://community.qlik.com/thread/155799 .

The exclamation mark moved from != to !resource. This caused otherwise the "SheetConditionalShow" to not work, but it might be my code. The full I use code is now (which works):
(resource.resourcetype = "App"
and resource.stream.HasPrivilege("read")
and resource.@AppExceptionFromStream.empty()
) or (
(
resource.resourcetype = "App.Object"
and resource.published = "true"
and resource.app.@SheetConditionalShow.empty()
and !resource.objectType = "app_appscript"
)
and resource.app.stream.HasPrivilege("read")
)

**Comment by goldbergjeffrey** [comment]
Updating docs with this change as well as many others I hope clarify things.  Will publish shortly.  Thanks for the catch.

**Comment by goldbergjeffrey** [comment]
resolved #30
